# Number of logs stored in RAM before saving into output file
buffer_size = 20000
# Folder containing reports
output_folder = "./data"
# Format of reports' filenames. Supported features:
# - timestamp  - time of report creation
# - number     - report's number
report_filename_format = "report_{timestamp}_{number}.csv"
# Type of reports. Supported types:
# - csv
report_type = "csv"
# Logging level. Possible values: "INFO", "WARNING", "ERROR"
log_level = "INFO"

[gps]
# Settings for GPS reader.

# Interface for GPS module
gps_port = "/dev/ttyS0"
# GPS baudrate
gps_baudrate = 9600
# Max time to wait for creation of stable GPS fix (in seconds)
timeout = 120.0
# Time to wait before retrying to get GPS fix after failure (in seconds)
retry_interval = 5.0

[web_server]
# Settings for built-in web server.

# Whether to start the web server. Use in case of critical load. 
# NOTE: Web server runs in a separate process, so it should not affect the main
# data reading process. However, if you are experiencing performance issues,
# you can disable the web server.
start_server = true
# Host to bind the web server to. Use "0.0.0.0" to bind to all interfaces.
host = "0.0.0.0"
# Port to listen on. Defaults to 8000, which is a common http port.
port = 8000
# Whether to set a password for accessing the web server. If true, the password
# specified in "password" field will be required to access the web server.
password_set = false
# Password for accessing the web server. Ignored if "password_set" is false.
password = "admin"
# Interval (in seconds) at which main thread will update data for web server. 
# This does not affect the actual data reading from the ADS1256 chip, which is 
# done in a separate thread and is not limited by this interval. Setting this 
# value too low may cause high CPU usage, while setting it too high may cause 
# the web server to display outdated data. A reasonable value is around 20 
# seconds, but you can adjust it based on your needs and performance 
# requirements.
data_update_interval = 20.0

[ads]
# Documentation for this settings can be found in "pipyadc" library docs:
# https://github.com/ul-gh/PiPyADC/blob/pigpio/examples/waveshare_board/waveshare_config.py
v_ref = 2.5
gain = 1
drate = 2000
active_channels = [0]

[ads.spi]
spi_bus = 0
spi_channel = 0
spi_frequency = 976563

[ads.pins]
cs_pin = 27
drdy_pin = 17
reset_pin = 18
pdwn_pin = 27
chip_select_gpios_initialize = [22, 23]

[ads.chip]
drdy_timeout = 2.0
drdy_delay = 0.000001
clkin_frequency = 7680000
chip_hard_reset_on_start = false
chip_id = 3
